version: '3.8'

services:
  mango-attendance:
    container_name: mango-attendance
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./src:/app/src
    restart: always
